#!/usr/bin/python
import os, sys
import ctypes
KIPR=ctypes.CDLL("/usr/lib/libkipr.so")

def main():

	black = 2900
	while(analog(0) < black or analog(3) < black): 
		if(analog(0) >= black and analog(3) < black): 
			motor(3,50)
			motor(0,-50)
			msleep(500)
		elif(analog(3) >= black and analog(0) < black):
			motor(0,50)
			motor(3,-50)
			msleep(500)
		else:
			motor(0,50)
			motor(3,50)
			msleep(500)

if __name__== "__main__":
    sys.stdout = os.fdopen(sys.stdout.fileno(),"w",0)
    main();
